### ISSUE TITLE
In Webhook Module Order Has Been Changed Event Trigger In Loop Again and Again

### ISSUE THREAD

**Issue by Koshalgarg155** [VirtoCommerce/vc-module-webhooks#58] opened 2022-08-30 07:01 UTC
Hi,
I have upgraded my platform from 3.66 to 3.240 and now my webhook module version is 3.201.
After Upgrading my webhook module, Order Has Been Changed Event is triggered again and again in the loop
and in one minute it triggers events sometimes 5 or sometimes 20 events for different orders and there is no change in orders. So How can I stop it

**Comment by OlegoO** [comment] 2022-08-30 07:07
As workaround: Try to remove web hook subscription and re-create it.

Please, share with us your webhook settings screenshot as platform manifest as well.

**Comment by OlegoO** [comment] 2022-08-30 07:18
@Koshalgarg155  Also, please check hangfire panel. Do you have any recurring jobs for Orders or Subscriptions which can trigger Order Has Been Changed Event ?

**Comment by mvktsk** [comment] 2022-08-30 07:23
Task https://virtocommerce.atlassian.net/browse/VP-8171 has been created

**Comment by Koshalgarg155** [comment] 2022-08-30 07:34
This is the webhook screenshot that i have created in platform
![image](https://user-images.githubusercontent.com/99241542/187377466-8bba75a8-af81-4325-b577-772c7d2ee503.png)

**Comment by Koshalgarg155** [comment] 2022-08-30 07:39
Hi @OlegoO ,
Where can I check the hangfire panel
and I think I don't have any recurring jobs for Orders or Subscriptions which can trigger Order Has Been Changed Event  but still how can I check it 
It was working fine in platform 3.66 after the upgrade it started to trigger events


Thank you for the response

**Comment by Koshalgarg155** [comment] 2022-08-30 07:48
This is the webhook screenshot that I have created in the platform.
I have tried deleting and creating a new webhook but still event is triggered again and again
![image](https://user-images.githubusercontent.com/99241542/187380457-3e49e25f-2e43-4a4a-9170-56dc4d4c2fdf.png)

**Comment by OlegoO** [comment] 2022-08-30 10:31
open virto commerce platfrom whith /hangfire path

**Comment by Koshalgarg155** [comment] 2022-08-30 10:37
this is the hangfire dashboard
![image](https://user-images.githubusercontent.com/99241542/187415895-dc7c91cb-7078-4800-96b7-ee3b91fd8940.png)

**Comment by Koshalgarg155** [comment] 2022-08-30 10:38
on 26 aug we have upgraded platform
![image](https://user-images.githubusercontent.com/99241542/187416174-d49859d9-a40a-4eb9-a278-8f9b5f438a4d.png)

**Comment by Koshalgarg155** [comment] 2022-08-30 10:43
I see now recurring jobs this is the screenshot of recurring jobs 
![image](https://user-images.githubusercontent.com/99241542/187416760-34509d53-db86-4bd1-b8c7-cbf76f87f368.png)


there is also this job triggered every 5 min with 40 request 
![image](https://user-images.githubusercontent.com/99241542/187432932-c1834e50-7b96-4ffa-bcaf-c246248e004b.png)

**Comment by OlegoO** [comment] 2022-08-30 13:59
@Koshalgarg155 we could not reproduce the problem.
Could you open platform information blade and Download manifest?

![image](https://user-images.githubusercontent.com/7639413/187456790-19774a3f-d8fa-4009-9e90-ffda77ab29d0.png)

**Comment by Koshalgarg155** [comment] 2022-08-31 04:39
@OlegoO  This is the manifest file
[vc-platform-info.zip](https://github.com/VirtoCommerce/vc-module-webhooks/files/9458460/vc-platform-info.zip)

**Comment by OlegoO** [comment] 2022-08-31 08:22
@Koshalgarg155  Do you use subscriptions?

**Comment by Koshalgarg155** [comment] 2022-08-31 08:33
yes i am using subscription module in platform

**Comment by Koshalgarg155** [comment] 2022-08-31 08:34
@OlegoO yes I am using the subscription module in platform for subscriptions

**Comment by OlegoO** [comment] 2022-08-31 11:45
@Koshalgarg155 
1. Open https://webhook.site/, copy **webhook unique URL**
2. Temporary reconfigure web hook on **webhook unique URL** and add IsPrototype
3. Run ProcessSubscriptionJob
4. Share with us Raw Content, like on the content below

I want to understand - is it either Customer Orders or Subscription Template modified?

**Comment by Koshalgarg155** [comment] 2022-08-31 11:57
@OlegoO I have configured a temporary webhook and i have also attached the raw content of the webhook order async
- > this is the raw content

[webhook content.txt](https://github.com/VirtoCommerce/vc-module-webhooks/files/9461262/webhook.content.txt)

![image](https://user-images.githubusercontent.com/99241542/187673005-163c2d0b-af63-4263-8366-1e7a326685f1.png)

**Comment by Koshalgarg155** [comment] 2022-08-31 12:12
@OlegoO  this is the webhook request that I receive in webhook
![image](https://user-images.githubusercontent.com/99241542/187675342-84efb3bf-6232-4a6b-bf94-9fb7ce8551f9.png)

**Comment by OlegoO** [comment] 2022-08-31 12:57
As workaround,  I recommend to add **IsPrototype** to your original event and check this property in logic app. If  IsPrototype == true, ignore event.

**Comment by Koshalgarg155** [comment] 2022-08-31 13:38
This issue is based on subscription and when the ProcessSubscriptionJob is executed, the same number of webhook events also gets fired.
can you tell me if you are planning to fix this with a new release?

**Comment by OlegoO** [comment] 2022-08-31 14:35
Yes, we are working under solution.

Subscription uses one of the order as template (IsPrototype = true) and modify them, so it's one of the reason why you see extra events.

**Comment by Koshalgarg155** [comment] 2022-08-31 15:31
Thank you @OlegoO

**Comment by Koshalgarg155** [comment] 2022-09-01 04:45
Hi @OlegoO,
I am facing one more issue in the storefront after the upgrade can you please check the ticket in storefront issues https://github.com/VirtoCommerce/vc-storefront/issues/618

**Comment by OlegoO** [comment] 2022-10-05 15:35
This issue will be resolved by release in Subscription module.

**Closed as completed by OlegoO** 2022-10-05 15:35 UTC
